from typing import Protocol

from kick_logs.domain.entities.channel import Channel


class ChannelRepository(Protocol):
    async def add(self, channel: Channel) -> Channel: ...

    async def update(self, channel: Channel) -> Channel: ...

    async def get_by_id(self, channel_id: int) -> Channel | None: ...

    async def get_by_slug(self, slug: str) -> Channel | None: ...

    async def list_enabled(self) -> list[Channel]: ...

    async def list_all(self) -> list[Channel]: ...
